FROM frolvlad/alpine-oraclejdk8:slim
#FROM openjdk:8
VOLUME /tmp
COPY build/libs/springbootthymepostgresdocker-0.1.0.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

