version: '2'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: sample
      POSTGRES_PASSWORD: pass
      POSTGRES_USERNAME: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
 
  spring-app:
    build:
      context: .
      dockerfile: dockerfile.spring
    ports:
      - "8080:8080"
    volumes:
      - .:/vol/development
   
    container_name: springdocker-app
    environment:
      POSTGRES: postgres
      POSTGRES_DB: sample
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: pass
    depends_on:
      - postgres
      
volumes:
  postgres: